apiVersion: tekton.dev/v1alpha1
kind: Pipeline
metadata:
  generation: 14
  name: aas-pipeline
spec:
  params:
    - default: 'https://github.com/kitty-catt/jboss-eap-quickstarts'
      description: the git repo to build
      name: git-repo
      type: string
    - default: 'master'
      description: the branch to build
      name: revision
      type: string
    - default: 'kitchensink'
      description: the specific maven module to build
      name: module
      type: string
  tasks:
    - name: fetch-repository
      params:
        - name: url
          value: $(params.git-repo)
        - name: subdirectory
          value: .
        - name: deleteExisting
          value: 'true'
      taskRef:
        kind: ClusterTask
        name: git-clone
      workspaces:
        - name: output
          workspace: shared-workspace
    - name: sonar-scan
      params:
        - name: module
          value: $(params.module)
      runAfter:
        - fetch-repository
      taskRef:
        kind: Task
        name: aas-sonar
      workspaces:
        - name: maven-settings
          workspace: maven-settings
        - name: source
          workspace: shared-workspace
        - name: maven-repo
          workspace: local-maven-repo             
    - name: source-2-war
      params:
        - name: GOALS
          value:
            - package
            - deploy
        - name: PROXY_PROTOCOL
          value: http
      runAfter:
        - sonar-scan
      taskRef:
        kind: Task
        name: aas-maven
      workspaces:
        - name: maven-settings
          workspace: maven-settings
        - name: source
          workspace: shared-workspace
        - name: maven-repo
          workspace: local-maven-repo          
  workspaces:
    - name: shared-workspace
    - name: maven-settings
    - name: local-maven-repo

