apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: aas-sonar
  annotations:
    description: Executes build, test, and sonarscan logic for a Java maven application
    app.openshift.io/description: Improved version of the ibm-garage-tekton-task
    app.openshift.io/vcs-uri: https://github.com/IBM/ibm-garage-tekton-tasks
    app.openshift.io/vcs-ref: master
  labels:
    version: 0.0.0
spec:
  params:
    - name: module
      default: 'no-kitchensink'
      description: "the module to scan"     
    - name: maven-image
      default: maven:3.6.3-jdk-11-slim
    - name: sonarqube-java-bin-path
      default: target
    - name: sonarqube-cli
      default: sonarsource/sonar-scanner-cli
  steps:
    - name: build
      image: $(params.maven-image)
      workingdir: $(workspaces.source.path)
      script: |
          mvn package -Dmaven.repo.local=$(workspaces.maven-repo.path)
    - name: test
      image: $(params.maven-image)
      workingdir: $(workspaces.source.path)
      script: |
          mvn test -Dmaven.repo.local=$(workspaces.maven-repo.path)
    - name: sonar-scan
      image: $(params.sonarqube-cli)
      # Genius Mod: just scan the child module
      workingdir: $(workspaces.source.path)/$(params.module)
      env:
        - name: SONAR_USER_HOME
          value: $(workspaces.source.path)
        - name: SONARQUBE_URL
          valueFrom:
            configMapKeyRef:
              name: sonarqube-config
              key: SONARQUBE_URL
              optional: true
        - name: SONARQUBE_PROJECT
          valueFrom:
            secretKeyRef:
              name: sonarqube-access
              key: SONARQUBE_PROJECT
              optional: true
        - name: SONARQUBE_LOGIN
          valueFrom:
            secretKeyRef: 
              name: sonarqube-access
              key: SONARQUBE_LOGIN
              optional: true
      script: |
          SONARQUBE_JAVA_BINARIES_PATH="$(params.sonarqube-java-bin-path)"
          if ! command -v sonar-scanner &> /dev/null
          then
              echo "Like to skip Skipping SonarQube step, because no task defined"
              #exit 0
              echo "Kitty-catt says: no, you don't"
          fi

          echo "scanning: $PWD/$(params.sonarqube-java-bin-path)"
          DIR=$(ls -l $PWD/$(params.sonarqube-java-bin-path))

          if [ -n "${SONARQUBE_URL}" ]; then
            sonar-scanner \
            -Dsonar.login=${SONARQUBE_LOGIN} \
            -Dsonar.host.url=${SONARQUBE_URL} \
            -Dsonar.projectKey=$(params.module) \
            -Dsonar.java.binaries=${SONARQUBE_JAVA_BINARIES_PATH}
          else
              echo "Skipping Sonar Qube because SONARQUBE_URL is not defined"
          fi
  workspaces:
    - name: source
    - name: maven-settings
    - name: maven-repo        